name: Deploy AWS Lightsail Container
description: Deploy container to AWS Lightsail Container Service
branding:
  icon: upload-cloud
  color: orange

inputs:
  image-name:
    description: Short name of the image
    required: true
  image:
    description: Full qualified tag of the image (registry/user/name:tag)
    required: true
  aws-region:
    description: AWS region
    required: true
  aws-access-key-id:
    description: AWS access key id
    required: true
  aws-access-key:
    description: AWS access key
    required: true
  aws-lightsail-service:
    description: AWS Lightsail service name
    required: true
  aws-lightsail-service-config:
    description: AWS Lightsail --cli-input-json service configuration
    required: true

runs:

  using: "composite"

  steps:

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Install AWS Lightsail plugin
      shell: bash
      run: |
        curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
        sudo chmod +x /usr/local/bin/lightsailctl

    - name: Clear Container Images
      shell: bash
      run: |
        echo 'IMAGES=$(aws lightsail get-container-images --region ${{ inputs.aws-region }} --service-name ${{ inputs.aws-lightsail-service }} --output text | grep -Eo ":${{ inputs.aws-lightsail-service }}\.${{ inputs.image-name }}\.\d+")' >> $GITHUB_ENV
        echo $IMAGES
        FIRST=0
        while read LINE; do
          if [ "$FIRST" -ne 0 ]; then
            aws lightsail delete-container-image --region ${{ inputs.aws-region }} --service-name ${{ inputs.aws-lightsail-service }} --image $LINE;
          fi
        FIRST=1;
        done <<< $IMAGES

#    - name: Publish image to AWS Lightsail
#      shell: bash
#      run: aws lightsail push-container-image --region ${{ inputs.aws-region }} --service-name ${{ inputs.aws-lightsail-service }} --label ${{ inputs.image-name }} --image ${{ inputs.image }}
#
#    - name: Deploy container on AWS Lightsail
#      shell: bash
#      run: aws lightsail create-container-service-deployment --region ${{ inputs.aws-region }} --cli-input-json '${{ inputs.aws-lightsail-service-config }}' > /dev/null
